apiVersion: v1
kind: Secret
metadata:
  name: db-connection
  namespace: flask-demo
  labels:
    app: flask-demo
    version: v1
type: Opaque
data:
  DB_NAME: demo
  DB_USERNAME: root
  DB_PASSWORD: password
  DB_HOST: 127.0.0.1
  DB_PORT: 9527
